**Feature Engineering**

- So far we have performed feature analysis

    - Data frame qucik check

    - Categorical column analsyis

    - Bar chart , Pie chart

    - Numberical column analysis

    - Histograms, box plots , outliers

    - correlation etc

- Now we need to learn Featue engineering

    - we will create a new columns for better ML models

    - we will perform the **Encoding**,which is convert categorical to Numerical data

    - we will do data **transformation**

    - we will perform **Scaling: Standardization and Normalization**

    - we will perform the **missing valu analysis**

- Simple feature engineering means our data will be modified

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [19]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

In [20]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [21]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [22]:
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

**case_status**

In [23]:
# how many unique labels
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [24]:
d={'Certified':0,'Denied':1}

In [25]:
visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [26]:
visa_df['case_status']=visa_df['case_status'].map(d)

In [27]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

**continent**

In [28]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [29]:
d={}
label=sorted(visa_df['continent'].unique())
for i,j in enumerate(label):
    #print(i,j)
    d[j]=i
print(d)

{'Certified': 0, 'Denied': 1, 'Africa': 0, 'Asia': 1, 'Europe': 2, 'North America': 3, 'Oceania': 4, 'South America': 5}

In [30]:
label=sorted(visa_df['continent'].unique())
d={i:j for j,i in enumerate(label)}
visa_df['continent']=visa_df['continent'].map(d)
# j → index (0, 1, 2)
# i → value ('Africa', 'Asia', 'Europe')

In [31]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [32]:
for i in cat[1:]:
    label=sorted(visa_df['continent'].unique())
    d={i:j for j,i in enumerate(label)}
    visa_df['continent']=visa_df['continent'].map(d)

In [33]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

- last class we perform the encodind

- we create a dictionary,we map to original data

- overwrite in the same column

- installation name:**sickit-learn**

- import name:**sklearn**

- library:**sklearn**

   - modules:**preprocessing**

     - class:**LabelEncoder**

        - method:**fit_transform**

In [35]:
import sklearn
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

In [36]:
sklearn

In [ ]:
# import the class 
# save the class
# apply fit transform

**fit vs fit_transform**

- if we are finding something then go for **fit**

- if we are finding some new value and using those values

- to modify the data then go for **fit + transform = fit_transform**

- we first developed a dictionary : **fit**

- we used the dictionary and change the data cat to num:**transform**

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [39]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

In [40]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

In [42]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [13]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['continent']=le.fit_transform(visa_df['continent'])

In [15]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [18]:
visa_df['continent'].unique()

array([1, 0, 3, 2, 5, 4])

In [51]:
for i in cat[1:]:
    from sklearn.preprocessing import LabelEncoder
    le=LabelEncoder()
    visa_df[i]=le.fit_transform(visa_df[i])

In [52]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**explore about inverse transform in the lab**

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
num = le.fit_transform(["A" ,"B","c"])
num

array([0, 1, 2])

In [34]:
le.inverse_transform(num)

array(['A', 'B', 'c'], dtype='<U1')

In [53]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

In [54]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [57]:
data=le.fit_transform(visa_df['education_of_employee'])

In [58]:
data[:5]

array([2, 3, 0, 0, 3])

In [59]:
le.inverse_transform(data)

array(['High School', "Master's", "Bachelor's", ..., "Master's",
       "Master's", "Bachelor's"], shape=(25480,), dtype=object)

In [28]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data=le.fit_transform(visa_df['education_of_employee'])

In [30]:
le.inverse_transform(data)

array(['High School', "Master's", "Bachelor's", ..., "Master's",
       "Master's", "Bachelor's"], shape=(25480,), dtype=object)

In [60]:
visa_df['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

- LabelEncoder use only for **Nominal level data**

- 90% target columns use only **LabelEncoder**

- for ordinal level data will go for **OrdinalEncoder**

- sklearn 

    - preprocessing

      - OrdinalEncoder

        - fit_transform

In [3]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')
visa_df['education_of_employee'].unique()
order=[['High School',"Bachelor's","Master's",'Doctorate']]

**One Hot Encoder**

- One hot means at a time only one value **ON**

- Other will be **OFF**

- ON means one value become **True**

- OFF means one value become **False**

- **True** means one value become **1**

- **False** means one valus become **0**

In [82]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=order)
oe.fit_transform(visa_df[['education_of_employee']])

array([[0.],
       [2.],
       [1.],
       ...,
       [2.],
       [2.],
       [1.]], shape=(25480, 1))

|Case_statues|Certified|Denied|
|---------|-------|---------|
|Certified|1|0|
|Denien|0|1|

**pd.get_dummies**

In [1]:
import pandas as pd

In [11]:
pd.get_dummies(visa_df["case_status"] )

       Certified  Denied
0          False    True
1           True   False
2          False    True
3          False    True
4           True   False
...          ...     ...
25475       True   False
25476       True   False
25477       True   False
25478       True   False
25479       True   False

[25480 rows x 2 columns]

In [12]:
pd.get_dummies(visa_df["case_status"],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [10]:
pd.get_dummies(visa_df["continent"],dtype=int)

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [27]:
pd.get_dummies(visa_df[cat[1:]],dtype=int)

,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,education_of_employee_Bachelor's,education_of_employee_Doctorate,education_of_employee_High School,education_of_employee_Master's,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,0,1,0,0,0,0,0,0,1,0,...,0,1,1,0,0,0,0,1,0,1
1,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
2,0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,1,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,1,0
25477,0,1,0,0,0,0,0,0,0,1,...,1,0,0,0,0,1,1,0,1,0
25478,0,1,0,0,0,0,0,0,0,1,...,0,1,0,0,0,1,0,1,1,0
25479,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [21]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

In [24]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [25]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')