**Step-1:import packages**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2:Create a Dataframe using list**

In [4]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrme(dta,index,columns)
pd.DataFrame(Names)

         0
0   Ramesh
1   Suresh
2  Sathish

In [2]:
import pandas as pd
Names=['Shiva','Bhanu','bharath']
pd.DataFrame(Names)

         0
0    Shiva
1    Bhanu
2  bharath

**Step-3:Name the column**

In [ ]:
Names=['Ramesh','Suresh','Sathish']
pd.DataFrame(Names,'NAME') # W
pd.DataFrame(Names,columns='NAME')  # W
pd.DataFrame(Names,['NAME']) # w
pd.DataFrame(Names,columns=['NAME']) # Right

In [9]:
Names=['Ramesh','Suresh','Sathish']
pd.DataFrame(Names,columns=['NAME'])

      NAME
0   Ramesh
1   Suresh
2  Sathish

In [3]:
import pandas as pd
Names=['Shiva','Bhanu','bharath']
pd.DataFrame(Names,columns=['NAME'])

      NAME
0    Shiva
1    Bhanu
2  bharath

**Step-4:Change the index**

In [12]:
Names=['Ramesh','Suresh','Sathish']
pd.DataFrame(Names,index=['A','B','C'],columns=['NAME'])

      NAME
A   Ramesh
B   Suresh
C  Sathish

In [4]:
import pandas as pd
Names=['Shiva','Bhanu','bharath']
pd.DataFrame(Names,index=['A','B','C'],columns=['Name'])

      Name
A    Shiva
B    Bhanu
C  bharath

**Step-5:Two columns**

In [15]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
pd.DataFrame(zip(Names,Age))

         0   1
0   Ramesh  20
1   Suresh  22
2  Sathish  24

In [6]:
import pandas as pd
Names=['Shiva','Bhanu','Bharath']
Age=[20,25,30]
pd.DataFrame(zip(Names,Age))

         0   1
0    Shiva  20
1    Bhanu  25
2  Bharath  30

In [11]:
import pandas as pd
Name=['Sumanth','Shiva','Vijith']
Age=[30,23,32]
pd.DataFrame(zip(Name,Age),columns=['Name','Age'],index=['A','B','C'])

      Name  Age
A  Sumanth   30
B    Shiva   23
C   Vijith   32

In [16]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
data=zip(Names,Age)
cols=['Names','Age']
pd.DataFrame(data,columns=cols)

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [14]:
import pandas as pd
Name=['shiva','sai','nani']
age=[20,21,24]
city=['hyd','mum','pune']
data=zip(Name,age,city)
cols=['Name','Age','City']
pd.DataFrame(data,columns=cols)

    Name  Age  City
0  shiva   20   hyd
1    sai   21   mum
2   nani   24  pune

**Step-6:Add the data to empty dataframe**

In [17]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [18]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [16]:
import pandas as pd
df=pd.DataFrame()
df['Name']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Delhi','Up']
df

      Name  Age   City
0   Ramesh   20    Hyd
1   Suresh   22  Delhi
2  Sathish   24     Up

In [21]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

**Step-7: Add the column to existed dataframe**

In [23]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Pune','Mumbai','Hyderabad']
df

     Names  Age       City
0   Ramesh   20       Pune
1   Suresh   22     Mumbai
2  Sathish   24  Hyderabad

In [14]:
import pandas as pd
Name=['Sumanth','Shiva','Vijith']
Age=[30,23,32]
City=['Hyd','Wng','Ngk']
pd.DataFrame(zip(Name,Age,City),columns=['Name','Age','City'],index=['A','B','C'])

      Name  Age City
A  Sumanth   30  Hyd
B    Shiva   23  Wng
C   Vijith   32  Ngk

**Step-8:Rename the column**

In [24]:
# I want to rename 'City' to 'city'
# df.rename(mapper,index,columns,axis,inplace)
d={'City':'city'}
df.rename(columns=d)

     Names  Age       city
0   Ramesh   20       Pune
1   Suresh   22     Mumbai
2  Sathish   24  Hyderabad

In [25]:
d={'Age':'age'}
df.rename(columns=d)

     Names  age       City
0   Ramesh   20       Pune
1   Suresh   22     Mumbai
2  Sathish   24  Hyderabad

In [27]:
d={'City':'city'}  # Column
df.rename(d)       # index
df.rename(d,axis=0) # index
df.rename(d,axis=1)  # col == work
df.rename(index=d)  # in
df.rename(columns=d) # column == work

     Names  Age       city
0   Ramesh   20       Pune
1   Suresh   22     Mumbai
2  Sathish   24  Hyderabad

In [28]:
df.columns=['names','age','City']

In [29]:
df.index=['A','B','C']

In [30]:
df

     names  age       City
A   Ramesh   20       Pune
B   Suresh   22     Mumbai
C  Sathish   24  Hyderabad

**Step-9:Drop the column**

In [31]:
# I want to drop 'City' column'
df.drop('City',axis=1)

     names  age
A   Ramesh   20
B   Suresh   22
C  Sathish   24

In [32]:
df.drop(columns=['City'])

     names  age
A   Ramesh   20
B   Suresh   22
C  Sathish   24

In [33]:
df.drop(index=['C'])

    names  age    City
A  Ramesh   20    Pune
B  Suresh   22  Mumbai

In [34]:
df.drop('City',axis=1,inplace=True)

In [35]:
df

     names  age
A   Ramesh   20
B   Suresh   22
C  Sathish   24

In [38]:
df.drop(index=['C'],axis=1,inplace=True)

In [39]:
df

    names  age
A  Ramesh   20
B  Suresh   22

In [ ]:
df.drop('city',axis=1,inplace=True)

In [ ]:
df.drop('City')  # error
df.drop('City',axis=0)  # error
df.drop(index=['City']) # error
df.drop('City',axis=1)  # work
df.drop(columns=['City']) # work

In [2]:
import pandas as pd
Name=['Shiva','Sumanth','Sai']
pd.DataFrame(Name)

         0
0    Shiva
1  Sumanth
2      Sai

In [5]:
import pandas as pd
Name=['Shiva','Sumanth','Sai']
Age=[20,21,25]
pd.DataFrame(zip(Name,Age))

         0   1
0    Shiva  20
1  Sumanth  21
2      Sai  25

In [16]:
import pandas as pd
Name=['Shiva','Sumanth','Sai']
Age=[20,21,25]
pd.DataFrame(zip(Name,Age),columns=['Name','Age'])

      Name  Age
0    Shiva   20
1  Sumanth   21
2      Sai   25

In [19]:
import pandas as pd
Name=['Nani','Shiva','Mani']
Age=[23,23,10]
pd.DataFrame(zip(Name,Age),columns=['Names','Ages'],index=['A','B','C'])

   Names  Ages
A   Nani    23
B  Shiva    23
C   Mani    10

In [21]:
import pandas as pd
Name=['Nani','Shiva','Mani']
Age=[23,23,11]
City=['Hyderabad','Nagarkurnool','Warangal']
pd.DataFrame(zip(Name,Age,City),columns=['Names','Ages','City'],index=['A','B','C'])

   Names  Ages          City
A   Nani    23     Hyderabad
B  Shiva    23  Nagarkurnool
C   Mani    11      Warangal

In [58]:
import pandas as pd
df=pd.DataFrame()
df['Name']=['Nani','Shiva','Mani']
df['Age']=[23,23,11]
df['City']=['Hyd','Ngk','Wng']
df

    Name  Age City
0   Nani   23  Hyd
1  Shiva   23  Ngk
2   Mani   11  Wng

In [59]:
df.drop(columns=['City'])

    Name  Age
0   Nani   23
1  Shiva   23
2   Mani   11

In [60]:
d={'City':'city'}
df.rename(columns=d)

    Name  Age city
0   Nani   23  Hyd
1  Shiva   23  Ngk
2   Mani   11  Wng

In [61]:
df.rename(d,axis=1)

    Name  Age city
0   Nani   23  Hyd
1  Shiva   23  Ngk
2   Mani   11  Wng

In [3]:
import pandas as pd
Names=['Ramesh','Suresh','Sathish']
City=['Hyd','Blr','Pune']
Age=[20,22,24]
data=zip(Names,City,Age)
df=pd.DataFrame(data,
             index=['A','B','C'],
             columns=['Names','City','Age'])
#####################################################
df.drop('City',axis=1,inplace=True)
df.drop('C',inplace=True)

In [4]:
df

    Names  Age
A  Ramesh   20
B  Suresh   22

- creating a dataframe

- Name the column

- Change the Index

- add the columns

- add the data to empty dataframe

- add the column to existing dataframe

- rename the column

- rename all the column and all the index at a time

- drop the column

- drop the index

In [5]:
# create a dataframe
import pandas as pd
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Blr','Pune']
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

**Step-10:replace**

In [7]:
# df.replace(to_replace,value)
df.replace('Hyd','Chennai') # inplace not happend so it will not overwrite

     Names  Age     City
0   Ramesh   20  Chennai
1   Suresh   22      Blr
2  Sathish   24     Pune

In [8]:
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [9]:
df['Names']='Mahesh'
df['Age']=24
df['City']='Hyd'

In [10]:
df

    Names  Age City
0  Mahesh   24  Hyd
1  Mahesh   24  Hyd
2  Mahesh   24  Hyd

In [11]:
import pandas as pd
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish','Mahesh']
df['Age']=[20,22,24,24]
df['City']=['Hyd','Blr','Pune','Hyd']
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune
3   Mahesh   24   Hyd

In [12]:
df.replace('Hyd','Chennai')

     Names  Age     City
0   Ramesh   20  Chennai
1   Suresh   22      Blr
2  Sathish   24     Pune
3   Mahesh   24  Chennai

In [13]:
df['Marks']=[25,24,23,22]

In [14]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     24
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [15]:
df.replace(24,20)

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     20
2  Sathish   20  Pune     23
3   Mahesh   20   Hyd     22

In [16]:
# all the data in same will change
# all the column data will change

df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     24
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [17]:
df['Marks'].replace(24,20,inplace=True)

C:\Users\Pebbeti Shiva prasad\AppData\Local\Temp\ipykernel_34860\602866676.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].replace(24,20,inplace=True)

In [18]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     20
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [19]:
# I want to change city name to Chennai
# for the candidates who has age = 24

**Step11-np.where**

In [20]:
import numpy as np

In [21]:
np.where(condition,True,False)
age==24
Chennai
Nochange

NameError: name 'condition' is not defined

In [22]:
df['City']=np.where(con,true,false)

NameError: name 'con' is not defined

In [23]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     20
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [24]:
# Big4
# Delloitte, EY, PWC,KPMG
#    SQL PANDAS 
# MAANG  : Micr AMA  APPL NV G
#          developer 
#          Skills DATA Structures
# create products 
#  SQL vs Pandas

**Step-12:Append a row**

In [25]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     20
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

**loc-iloc**

In [ ]:
df.loc[rows,columns]
  rows are index numbers similar to list slice
  l[start:stop:step]
  column are names any column name we can provide
df.iloc[rows,columns]
  rows and columns are index numbers similar to list slice
  l[start:stop:step]

In [27]:
rows=[1,2,3]
cols=['Age','City']
df.loc[rows,cols]

   Age  City
1   22   Blr
2   24  Pune
3   24   Hyd

In [28]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22   Blr     20
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [29]:
rows=[1,2,3]
cols=[1,2]
df.iloc[rows,cols]

   Age  City
1   22   Blr
2   24  Pune
3   24   Hyd

In [30]:
cols=['Age','City']
df.loc[1:3,cols]

   Age  City
1   22   Blr
2   24  Pune
3   24   Hyd

In [31]:
df.loc[len(df)]=['Anish',26,'Mumbai',25]

In [32]:
df

     Names  Age    City  Marks
0   Ramesh   20     Hyd     25
1   Suresh   22     Blr     20
2  Sathish   24    Pune     23
3   Mahesh   24     Hyd     22
4    Anish   26  Mumbai     25

**Step-13:How to save the dataframe**

In [33]:
# directory : where is the file available
# name      : what is the name of the file
# extension : what is the type of the file 

####################################
#      SAME PYTHON LOCATION        #
# name      : what is the name of the file
# extension : what is the type of the file 

# dataframe variable = df
# name : student
# exten : .csv  and .xlsx 

df.to_csv('student.csv')

In [34]:
pd.read_csv('student.csv')

   Unnamed: 0    Names  Age    City  Marks
0           0   Ramesh   20     Hyd     25
1           1   Suresh   22     Blr     20
2           2  Sathish   24    Pune     23
3           3   Mahesh   24     Hyd     22
4           4    Anish   26  Mumbai     25

**Step-14:Ignore index**

In [35]:
df.to_csv('student.csv',index=False)

In [36]:
pd.read_csv('student.csv')

     Names  Age    City  Marks
0   Ramesh   20     Hyd     25
1   Suresh   22     Blr     20
2  Sathish   24    Pune     23
3   Mahesh   24     Hyd     22
4    Anish   26  Mumbai     25

In [37]:
df.to_excel('student.xlsx')

In [38]:
pd.read_excel('student.xlsx')

   Unnamed: 0    Names  Age    City  Marks
0           0   Ramesh   20     Hyd     25
1           1   Suresh   22     Blr     20
2           2  Sathish   24    Pune     23
3           3   Mahesh   24     Hyd     22
4           4    Anish   26  Mumbai     25

In [39]:
# take a new notebook
# in your datafiles
#   visadataset
#   bankdataset pls load that

In [17]:
import pandas as pd
Name=['shiva','bharath','mani']
Age=[24,14,11]
City=['klk','Mmd','ngkl']
data=zip(Name,Age,City)
cols=['Name','Age','City']
pd.DataFrame(data,columns=cols,index=['A','B','C'])

      Name  Age  City
A    shiva   24   klk
B  bharath   14   Mmd
C     mani   11  ngkl

In [18]:
df['marks']=[95,96,98]
df

      Name  Age   City  marks
0   Ramesh   20    Hyd     95
1   Suresh   22  Delhi     96
2  Sathish   24     Up     98

In [22]:
d={'City':'city'}
df.rename(columns=d)

      Name  Age   city  marks
0   Ramesh   20    Hyd     95
1   Suresh   22  Delhi     96
2  Sathish   24     Up     98

In [24]:
df.replace(22,23)

      Name  Age   City  marks
0   Ramesh   20    Hyd     95
1   Suresh   23  Delhi     96
2  Sathish   24     Up     98

In [36]:
import pandas as pd
df=pd.DataFrame()
df['Name']=['shiva','bharath','mani']
df['Age']=[24,14,11]
df['City']=['Klk','MMD','NGKL']

In [37]:
df['Marks']=[23,21,18]
df

      Name  Age  City  Marks
0    shiva   24   Klk     23
1  bharath   14   MMD     21
2     mani   11  NGKL     18