In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
np.__version__

'2.3.5'

In [19]:
pd.__version__

'2.3.3'

In [20]:
import matplotlib
!pip show matplotlib

Name: matplotlib
Version: 3.10.6
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: Unknown <matplotlib-users@python.org>
License: License agreement for matplotlib versions 1.3.0 and later
 =========================================================

 1. This LICENSE AGREEMENT is between the Matplotlib Development Team
 ("MDT"), and the Individual or Organization ("Licensee") accessing and
 otherwise using matplotlib software in source or binary form and its
 associated documentation.

 2. Subject to the terms and conditions of this License Agreement, MDT
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that MDT's
 License Agreement and MDT's notice of copyright, i.e., "Copyright (c)
 2012- Matplotlib Development Team; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib .

 4. MDT is making matplotlib available to Licensee on an "AS
 IS" basis.  MDT MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, MDT MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. MDT SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between MDT and
 Licensee.  This License Agreement does not grant permission to use MDT
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib ,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.

 License agreement for matplotlib versions prior to 1.3.0
 ========================================================

 1. This LICENSE AGREEMENT is between John D. Hunter ("JDH"), and the
 Individual or Organization ("Licensee") accessing and otherwise using
 matplotlib software in source or binary form and its associated
 documentation.

 2. Subject to the terms and conditions of this License Agreement, JDH
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that JDH's
 License Agreement and JDH's notice of copyright, i.e., "Copyright (c)
 2002-2011 John D. Hunter; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib  or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib.

 4. JDH is making matplotlib  available to Licensee on an "AS
 IS" basis.  JDH MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, JDH MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. JDH SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between JDH and
 Licensee.  This License Agreement does not grant permission to use JDH
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.
Location: C:\Users\Pebbeti Shiva prasad\anaconda3\Lib\site-packages
Requires: contourpy, cycler, fonttools, kiwisolver, numpy, packaging, pillow, pyparsing, python-dateutil
Required-by: ipympl, seaborn, wordcloud

In [21]:
sns.__version__

'0.13.2'

In [22]:
pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [23]:
visa_df=pd.read_csv(r'C:\Users\Pebbeti Shiva prasad\OneDrive\Desktop\Datafiles\visadataset.csv')

- head

- tail

- shape

- columns

- dtypes

In [24]:
visa_df.head(10)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.1400,Year,Y,Certified
6,EZYV07,Asia,Bachelor's,N,N,4985,1994,South,53635.3900,Year,Y,Certified
7,EZYV08,North America,Bachelor's,Y,N,3035,1924,West,418.2298,Hour,Y,Denied
8,EZYV09,Asia,Bachelor's,N,N,4810,2012,Midwest,74362.1900,Year,Y,Certified
9,EZYV10,Europe,Doctorate,Y,N,2251,1995,South,67514.7600,Year,Y,Certified

In [26]:
visa_df.tail(11)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25469,EZYV25470,North America,Master's,Y,N,2261,1997,Northeast,273772.4700,Year,N,Certified
25470,EZYV25471,North America,Master's,Y,N,2272,1970,Northeast,516.4101,Hour,Y,Certified
25471,EZYV25472,Asia,High School,N,N,40224,1962,Island,75587.4200,Year,Y,Certified
25472,EZYV25473,Asia,High School,N,N,1346,2003,Midwest,76155.6000,Year,N,Certified
25473,EZYV25474,Asia,Bachelor's,Y,N,2421,2007,Northeast,22845.5600,Year,Y,Certified
25474,EZYV25475,Africa,Doctorate,N,N,2594,1979,Northeast,51104.7800,Year,Y,Certified
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [27]:
visa_df.shape

(25480, 12)

In [28]:
print(f"the number of rows are:{visa_df.shape[0]}")
print(f"the number of rows are:{visa_df.shape[1]}")

the number of rows are:25480
the number of rows are:12

In [29]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [30]:
type(visa_df)

pandas.core.frame.DataFrame

In [31]:
type(visa_df.columns)

pandas.core.indexes.base.Index

In [32]:
cols=visa_df.columns
cols.tolist().index('continent')

1

**dtype**

In [33]:
visa_df.dtype()

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [34]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [35]:
visa_df.case_id

0           EZYV01
1           EZYV02
2           EZYV03
3           EZYV04
4           EZYV05
           ...
25475    EZYV25476
25476    EZYV25477
25477    EZYV25478
25478    EZYV25479
25479    EZYV25480
Name: case_id, Length: 25480, dtype: object

In [36]:
visa_df.continent

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [37]:
visa_df.education_of_employee

0        High School
1           Master's
2         Bachelor's
3         Bachelor's
4           Master's
            ...
25475     Bachelor's
25476    High School
25477       Master's
25478       Master's
25479     Bachelor's
Name: education_of_employee, Length: 25480, dtype: object

In [38]:
data_types=visa_df.dtypes
type(data_types)

pandas.core.series.Series

In [39]:
type(visa_df)

pandas.core.frame.DataFrame

In [40]:
data_types.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [41]:
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

- series is a key value pair

- series kind of a dictionary

In [67]:
data_types.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [43]:
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [44]:
data_types.keys()
data_types.values
##############################
data_types.index
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

- When we have a series

- we need to make to seperate lists

- so that we can able to create a dataframe

In [51]:
visa_df
visa_df.dtypes
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
df1=pd.DataFrame(zip(keys,values),columns=['Continates','Data Types'])
df1

               Continates Data Types
0                 case_id     object
1               continent     object
2   education_of_employee     object
3      has_job_experience     object
4   requires_job_training     object
5         no_of_employees      int64
6             yr_of_estab      int64
7    region_of_employment     object
8         prevailing_wage    float64
9            unit_of_wage     object
10     full_time_position     object
11            case_status     object

In [52]:
# idea 
# extract key and values
# apply the for loop
# check the condition if the data type=object then
#  append in cat list
#  otherwise append in num list

In [60]:
keys = visa_df.dtypes.keys()
values = visa_df.dtypes.values
cat = []
num = []
for i,j in zip(keys,values):
    print(i,j)
    if j=='object':
        cat.append(i)
    else:
        num.append(i)

case_id object
continent object
education_of_employee object
has_job_experience object
requires_job_training object
no_of_employees int64
yr_of_estab int64
region_of_employment object
prevailing_wage float64
unit_of_wage object
full_time_position object
case_status object

In [63]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat = []
num = []
for i,j in zip(keys,values):
    print(i,j)
    if i=='object':
        cat.append(i)
    else:
        num.append(i)

case_id object
continent object
education_of_employee object
has_job_experience object
requires_job_training object
no_of_employees int64
yr_of_estab int64
region_of_employment object
prevailing_wage float64
unit_of_wage object
full_time_position object
case_status object

In [64]:
cat,num

([],
 ['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'no_of_employees',
  'yr_of_estab',
  'region_of_employment',
  'prevailing_wage',
  'unit_of_wage',
  'full_time_position',
  'case_status'])

In [66]:
visa_df.iloc[100:105,3:7] # dataframe

    has_job_experience requires_job_training  no_of_employees  yr_of_estab
100                  Y                     N             2227         2007
101                  Y                     N              334         2007
102                  Y                     N              224         2008
103                  Y                     N              367         1982
104                  Y                     N              306         2003

In [67]:
visa_df.iloc[100]  # series

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [68]:
visa_df.iloc[[100]]  # dataframe

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [69]:
visa_df.iloc[[100,200,300],]  # dataframe

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [70]:
visa_df.iloc[[100,200,300],:]  # dataframe

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [71]:
visa_df.iloc[:,[3,6,9]]  # dataframe

      has_job_experience  yr_of_estab unit_of_wage
0                      N         2007         Hour
1                      Y         2002         Year
2                      N         2008         Year
3                      N         1897         Year
4                      Y         2005         Year
...                  ...          ...          ...
25475                  Y         2008         Year
25476                  Y         2006         Year
25477                  Y         1910         Year
25478                  Y         1887         Year
25479                  Y         1960         Year

[25480 rows x 3 columns]

In [72]:
visa_df.iloc[:,3] # series

0        N
1        Y
2        N
3        N
4        Y
        ..
25475    Y
25476    Y
25477    Y
25478    Y
25479    Y
Name: has_job_experience, Length: 25480, dtype: object

In [73]:
visa_df.iloc[:,[3]]  # dataframe

      has_job_experience
0                      N
1                      Y
2                      N
3                      N
4                      Y
...                  ...
25475                  Y
25476                  Y
25477                  Y
25478                  Y
25479                  Y

[25480 rows x 1 columns]

In [74]:
visa_df.iloc[:,:]  # dataframe

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [66]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat=[]
num=[]
for i,j in zip(keys,values):
    print(i,j)
    if i=='object':
        cat.append(i)
    else:
        num.append(i)
cat,num

case_id object
continent object
education_of_employee object
has_job_experience object
requires_job_training object
no_of_employees int64
yr_of_estab int64
region_of_employment object
prevailing_wage float64
unit_of_wage object
full_time_position object
case_status object

([],
 ['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'no_of_employees',
  'yr_of_estab',
  'region_of_employment',
  'prevailing_wage',
  'unit_of_wage',
  'full_time_position',
  'case_status'])